### ISSUE TITLE
Timeout while getting recordings

### ISSUE THREAD

**Issue by felcaetano** [zbx-sadman/BigBlueButton#2]
On a server with a large number of recordings (we have 2000+ for instance), the server takes more than the configurable 30 seconds before a times out occurs.
Changing the max timeout on Zabbix source code is impractical. 
Making it an active check does not solve the issue. 
There must be a way to make it asynchronous (without using cron preferably).

**Comment by zbx-sadman** [comment]
So... I don't know sraight way to achieve long poller's runtime.

I guess that you can make try to use special script with ``system.run[command,<mode>]``, where mode is ``nowait`` (refer to [manual](https://www.zabbix.com/documentation/4.4/manual/config/items/itemtypes/zabbix_agent)). This script must call wget and push out data to Zabbix server  with ``zabbix_sender`` to the Item with [trapper](https://www.zabbix.com/documentation/4.4/manual/config/items/itemtypes/trapper) type
