### ISSUE TITLE
LLD not working on some cases. 

### ISSUE THREAD

**Issue by felcaetano** [zbx-sadman/BigBlueButton#3]
LLD is not working for some meetingIDs.
I figured this out because every meetingID generated by the Moodle plugin has a dash "-" on it and they were not showing up on LLD.

According to BBB documentation:

> Meeting IDs should only contain upper/lower ASCII letters, numbers, dashes, or underscores. A good choice for the meeting ID is to generate a GUID value as this all but guarantees that different meetings will not have the same meetingID.

But meetingID might even have spaces in some cases  (e.g. "Demo meeting").

My suggestion is changing "(\w+)" for something more broad in:

https://github.com/zbx-sadman/BigBlueButton/blob/f68ef2f2a7504ae7baa193e07852ea52289baf49/Zabbix_Templates/TemplateAppBigBlueButtonServer.xml#L1860

and 

https://github.com/zbx-sadman/BigBlueButton/blob/f68ef2f2a7504ae7baa193e07852ea52289baf49/Zabbix_Templates/TemplateAppBigBlueButtonServer.xml#L1863

I did change it to "(.*)" for testing and it worked, but I don't feel comfortable using this as a solution.

**Comment by zbx-sadman** [comment]
Actually I use LLD in the very rare cases - ours sessions not recording in general.

I have an idea: `\w+` matches one or more word characters (same as `[a-zA-Z0-9_]+`). Hence, we can replace `\w+` to the `[a-zA-Z0-9_-]+`  in order to strictly follow the BBB meeting ID format.

And I have no seen meetingID like "Demo meeting". May be it meeting name? But you can add `\s` to the foresaid `\w+` replacement: `[a-zA-Z0-9_-]+` if you wish.

I will be grateful for testing, and i will change code in the template on success.

**Comment by felcaetano** [comment]
Yeah, I double-checked.
![demo](https://user-images.githubusercontent.com/29981801/120222447-55d4a380-c216-11eb-90c2-ec211ea29e66.png)

I changed it to "[a-zA-Z0-9_-]+" and It worked for the Moodle plugin. Would be interesting to at least check how Greenlight generate it's meetingID's to make sure this template is compatible.

**Comment by zbx-sadman** [comment]
I use Greenlight 2.x , and this is an example of Id: ``bzdxuw15g8x0efp2gw7mikreyci4iju5dkbrffdh``. Zabbix key is ``bbb.participantsCount[bzdxuw15g8x0efp2gw7mikreyci4iju5dkbrffdh]``

So, i will change ``(\w+)`` to ``([a-zA-Z0-9_-]+)`` or just to ``([\w_-]+)``, right?

**Comment by felcaetano** [comment]
> So, i will change `(\w+)` to `([a-zA-Z0-9_-]+)` or just to `([\w_-]+)`, right?

Seems fine for me.

Indeed Greenlight ID is 40 alphanumeric characters. 

https://github.com/bigbluebutton/greenlight/blob/cb1bda5db0c238c1b7d0fb4285f6bb0ed966be58/app/models/room.rb#L122

**Comment by zbx-sadman** [comment]
Changes applied.
