### ISSUE TITLE
Import of TemplateAppBigBlueButtonServer-macrosed.xml in Zabbix 5.0 fails with error

### ISSUE THREAD

**Issue by a-schild** [zbx-sadman/BigBlueButton#4]
Importing the LLD template (TemplateAppBigBlueButtonServer-macrosed.xml) in Zabbix 5.0 gives this error:

```
Details Import fehlgeschlagen
    Keine Wertezuordnung "bbb.participantsCount[{#ID}]" auf "Template App BigBlueButton Server" gefunden, für Datenpunktvorlage "[{#NAME}] Participants summary" der Suchlaufregel "Meetings" auf "Template App BigBlueButton Server1".
```

In english something like "No value assignement for "bbb.participantsCount[{#ID}]" found in "Template App BigBlueButton Server", for value point template "[{#NAME}] Participants summary" in search run "Meetings" on "Template App BigBlueButton Server1"

**Comment by zbx-sadman** [comment]
Hello André 

Thanks for template testing.  This is silly error - wrong template name placed into .xml (Server1 instead Server). I've already fixed it on repository.

**Comment by a-schild** [comment]
Works fine.
Thanks for the fast fix
